name: Deploy to Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual deployment"
        required: false
        type: string
        default: "Manual trigger"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -H 18.234.218.237 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ubuntu@18.234.218.237 << 'EOF'
            # Go to project directory
            cd foodify-website

            # Pull the latest code
            git pull

            # Build, tear down, and recreate containers
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --force-recreate

            # Build the frontend inside the container
            docker exec -i foodify-website-app-1 bash -c "cd app && npm run build"

            # Restart app container
            docker compose -f docker-compose.prod.yml restart app
          EOF
