name: Deploy to Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual deployment"
        required: false
        type: string
        default: "Manual trigger"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 18.234.218.237 >> ~/.ssh/known_hosts

      - name: Run deployment
        run: |
          ssh -v -i ~/.ssh/id_rsa ubuntu@18.234.218.237 << 'EOF'
            # Go to project directory
            cd foodify-website

            # Pull the latest code
            git pull

            # Build, tear down, and recreate containers
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --force-recreate

            # Build the frontend inside the container
            docker exec -i foodify-website-app-1 bash -c "cd app && npm run build"

            # Restart app container
            docker compose -f docker-compose.prod.yml restart app
          EOF
