name: Deploy to Production

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual deployment"
        required: false
        type: string
        default: "Manual trigger"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 18.234.218.237
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Go to project directory
            cd foodify-website

            # Pull the latest code
            git pull

            # Build, tear down, and recreate containers
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --force-recreate

            # Build the frontend inside the container
            docker exec -i foodify-website-app-1 bash -c "cd app && npm run build"

            # Restart app container
            docker compose -f docker-compose.prod.yml restart app
